/**
 * AI TOOLS DEFINITIONS & EXECUTION
 *
 * This file defines the "functions" that the LLM can call during a chat.
 * It also handles the actual execution of these tools using vector search (Pinecone)
 * and graph queries (Neo4j).
 */

import { PineconeService } from "@/services/pinecone.services";
import { getNeo4jDriver } from "./neo4j";
import { generateEmbeddings } from "@/llm/embeddings";

/**
 * TOOL DEFINITIONS
 * These are passed to the OpenAI/Anthropic API to describe what capabilities the agent has.
 */
export const aiTools = [
  {
    type: "function",
    function: {
      name: "search_codebase",
      description:
        "Search for relevant code snippets in the codebase using semantic vector search. Returns file paths and short snippets. Use this when you don't know the exact file path or are looking for specific functionality.",
      parameters: {
        type: "object",
        properties: {
          // The semantic query (e.g., "how is authentication handled?")
          query: {
            type: "string",
            description: "The natural language query to search for code.",
          },
        },
        required: ["query"],
      },
    },
  },
  {
    type: "function",
    function: {
      name: "get_file_content",
      description:
        "Retrieve the full content of a specific file. Use this after you have a file path from search_codebase or list_files and need to see the complete logic.",
      parameters: {
        type: "object",
        properties: {
          // Relative path from the repo root
          path: {
            type: "string",
            description:
              "The file path relative to the repository root (e.g., 'app/page.tsx').",
          },
        },
        required: ["path"],
      },
    },
  },
  {
    type: "function",
    function: {
      name: "list_files",
      description:
        "List all files and directory structure in the codebase. Use this to understand the project layout, routing structure (e.g., app directory), or to find specific configuration files.",
      parameters: {
        type: "object",
        properties: {
          // Optional sub-directory to narrow the search
          directory: {
            type: "string",
            description:
              "Optional directory to list (e.g., 'app'). If omitted, lists the top-level structure.",
          },
        },
      },
    },
  },
  {
    type: "function",
    function: {
      name: "query_graph_relations",
      description:
        "Query relationships between files/modules in the codebase using Cypher on Neo4j. Useful for complex architectural analysis like finding all dependencies of a module.",
      parameters: {
        type: "object",
        properties: {
          // Raw Cypher query that the LLM generates
          cypher: { type: "string", description: "The Cypher query to run." },
        },
        required: ["cypher"],
      },
    },
  },
];

/**
 * EXECUTE TOOL
 * The dispatcher that runs the logic associated with each tool call.
 *
 * @param name The name of the tool being called
 * @param args The arguments generated by the LLM
 * @param codebaseId The ID of the codebase currently being chatted with
 * @param signal AbortSignal to cancel long-running database queries if the user stops the stream
 */
export async function executeTool(
  name: string,
  args: Record<string, unknown>,
  codebaseId: string,
  signal?: AbortSignal,
) {
  // TOOL 1: SEARCH CODEBASE (Vector Search)
  if (name === "search_codebase") {
    const query = args.query as string;
    console.log(
      `[Tool: search_codebase] Query: "${query}" | Codebase: ${codebaseId}`,
    );

    // Convert the natural language query into a vector embedding
    const embedding = await generateEmbeddings(query, signal);

    signal?.throwIfAborted();

    // Connect to Pinecone and query the specific codebase's items
    const index = PineconeService.getInstance().getIndex();
    const result = await index.query({
      vector: embedding,
      topK: 5, // Return top 5 most relevant results
      filter: { codebaseId: { $eq: codebaseId } }, // Ensure we only see results from THIS repo
      includeMetadata: true,
    });

    console.log(
      `[Tool: search_codebase] Found ${result.matches.length} matches in Pinecone`,
    );

    // Return a cleaned-up object for the LLM to digest
    return result.matches.map((m) => ({
      path: m.metadata?.path,
      snippet: m.metadata?.contentSnippet,
      score: m.score,
    }));
  }

  // TOOL 2: GET FILE CONTENT (Direct Graph Lookup)
  if (name === "get_file_content") {
    const path = args.path as string;
    console.log(
      `[Tool: get_file_content] Path: "${path}" | Codebase: ${codebaseId}`,
    );

    signal?.throwIfAborted();
    const driver = getNeo4jDriver();
    const session = driver.session();

    try {
      // Fetch the 'content' property from the 'File' node in Neo4j
      const result = await session.executeRead((tx) =>
        tx.run(
          `
          MATCH (f:File {path: $path, codebaseId: $codebaseId})
          RETURN f.content as content
          `,
          { codebaseId, path },
        ),
      );

      // Return the raw text if found
      if (result.records.length > 0) {
        return { path, content: result.records[0].get("content") };
      }

      return { error: "File not found in the indexed database." };
    } catch (err: unknown) {
      console.error(`Error fetching file from Neo4j ${path}:`, err);
      return {
        error: `Failed to fetch file content from database: ${(err as Error).message || String(err)}`,
      };
    } finally {
      await session.close();
    }
  }

  // TOOL 3: LIST FILES (Prefix Search)
  if (name === "list_files") {
    const { directory = "" } = args;
    console.log(
      `[Tool: list_files] Dir: "${directory}" | Codebase: ${codebaseId}`,
    );

    signal?.throwIfAborted();
    const driver = getNeo4jDriver();
    const session = driver.session();

    try {
      // Uses Neo4j to find all File nodes whose path starts with the given prefix
      const result = await session.executeRead((tx) =>
        tx.run(
          `
          MATCH (f:File {codebaseId: $codebaseId})
          WHERE f.path STARTS WITH $prefix
          RETURN f.path as path LIMIT 200
          `,
          {
            codebaseId,
            prefix: directory
              ? (directory as string).endsWith("/")
                ? directory
                : directory + "/"
              : "",
          },
        ),
      );

      const paths = result.records.map((r) => r.get("path"));
      return { paths, count: paths.length };
    } finally {
      await session.close();
    }
  }

  // TOOL 4: QUERY GRAPH RELATIONS (Advanced Architecture Lookup)
  if (name === "query_graph_relations") {
    const cypher = args.cypher as string;
    console.log(
      `[Tool: query_graph_relations] Cypher: "${cypher}" | Codebase: ${codebaseId}`,
    );

    signal?.throwIfAborted();
    const driver = getNeo4jDriver();
    const session = driver.session();

    try {
      // Runs the raw Cypher query generated by the LLM (it understands our Neo4j schema)
      const result = await session.executeRead((tx) =>
        tx.run(cypher, { codebaseId }),
      );
      console.log(
        `[Tool: query_graph_relations] Returned ${result.records.length} records from Neo4j`,
      );

      // Convert records to plan JS objects for easy LLM parsing
      return result.records.map((r) => r.toObject());
    } finally {
      await session.close();
    }
  }

  throw new Error(`Tool ${name} not found`);
}
